"""
Reusable UI helper functions for rendering analysis results.
"""

from src.analysis.schemas import FullAnalysisResult, ClauseRisk, RiskLevel

_RISK_EMOJI = {
    "LOW": "🟢",
    "MEDIUM": "🟡",
    "HIGH": "🔴",
    "CRITICAL": "⛔",
}

_RISK_COLOR = {
    "LOW": "#22c55e",
    "MEDIUM": "#f59e0b",
    "HIGH": "#ef4444",
    "CRITICAL": "#7f1d1d",
}


def render_risk_badge(risk_level: str) -> str:
    emoji = _RISK_EMOJI.get(risk_level, "⚪")
    return f"{emoji} **{risk_level}**"


def render_document_summary_md(result: FullAnalysisResult) -> str:
    """Render the document-level summary as Markdown."""
    s = result.document_summary
    risk_emoji = _RISK_EMOJI.get(s.overall_risk_level.value, "⚪")

    lines = [
        f"# {risk_emoji} Contract Risk Analysis: {result.filename}",
        "",
        f"**Contract Type:** {s.contract_type}  |  "
        f"**Overall Risk:** {risk_emoji} {s.overall_risk_level.value}  |  "
        f"**Risk Score:** {s.overall_risk_score:.1f}/10",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        s.executive_summary,
        "",
        "## Risk Breakdown",
        "",
        f"| Risk Level | Count |",
        f"|------------|-------|",
        f"| ⛔ CRITICAL | {sum(1 for c in result.clause_analyses if c.risk_level == RiskLevel.CRITICAL)} |",
        f"| 🔴 HIGH | {sum(1 for c in result.clause_analyses if c.risk_level == RiskLevel.HIGH)} |",
        f"| 🟡 MEDIUM | {result.medium_risk_count} |",
        f"| 🟢 LOW | {result.low_risk_count} |",
        f"| **Total Analyzed** | **{result.total_clauses_analyzed}** |",
        "",
    ]

    if s.critical_issues:
        lines += [
            "## ⚠️ Critical Issues",
            "",
            *[f"- {issue}" for issue in s.critical_issues],
            "",
        ]

    if s.party_analysis:
        lines += [
            "## Party Risk Analysis",
            "",
            s.party_analysis,
            "",
        ]

    if s.missing_clauses:
        lines += [
            "## 🚨 Missing Standard Clauses",
            "",
            "| Clause Type | Risk | Description |",
            "|-------------|------|-------------|",
            *[
                f"| {m.clause_type.replace('_', ' ').title()} | "
                f"{_RISK_EMOJI.get(m.risk_level.value, '⚪')} {m.risk_level.value} | "
                f"{m.description[:80]}... |"
                for m in s.missing_clauses
            ],
            "",
        ]

    if s.positive_observations:
        lines += [
            "## ✅ Positive Observations",
            "",
            *[f"- {obs}" for obs in s.positive_observations],
            "",
        ]

    return "\n".join(lines)


def render_clause_analysis_md(clauses: list[ClauseRisk]) -> str:
    """Render all clause analyses as expandable Markdown sections."""
    if not clauses:
        return "_No clauses were analyzed._"

    lines = ["# Clause-by-Clause Analysis", ""]

    for i, clause in enumerate(clauses, 1):
        risk_emoji = _RISK_EMOJI.get(clause.risk_level.value, "⚪")
        conf_pct = int(clause.confidence_score * 100)

        lines += [
            f"---",
            f"## {i}. {clause.clause_type.replace('_', ' ').title()} — {risk_emoji} {clause.risk_level.value}",
            f"*Confidence: {conf_pct}%*",
            "",
            "**Original Clause:**",
            f"> {clause.clause_text[:400]}{'...' if len(clause.clause_text) > 400 else ''}",
            "",
            f"**Risk Assessment:** {clause.risk_description}",
            "",
        ]

        if clause.key_concerns:
            lines += [
                "**Key Concerns:**",
                *[f"- {concern}" for concern in clause.key_concerns],
                "",
            ]

        if clause.reference_clause:
            lines += [
                "**Standard Reference:**",
                f"> {clause.reference_clause[:300]}{'...' if len(clause.reference_clause) > 300 else ''}",
                f"*Source: {clause.source_citation}*",
                "",
            ]

        if clause.suggested_revision:
            lines += [
                "**💡 Suggested Revision:**",
                clause.suggested_revision,
                "",
            ]

    return "\n".join(lines)


def render_export_report(result: FullAnalysisResult) -> str:
    """Full Markdown report for download."""
    summary = render_document_summary_md(result)
    clauses = render_clause_analysis_md(result.clause_analyses)

    disclaimer = (
        "\n\n---\n\n"
        "**LEGAL DISCLAIMER:** This analysis is AI-generated for informational purposes only. "
        "It does not constitute legal advice. Consult a qualified attorney before acting on any "
        "information contained in this report.\n\n"
        "*Generated by AI Legal Contract Analyzer*"
    )

    return summary + "\n\n" + clauses + disclaimer
