"""
Legal disclaimer injection.

Every output that reaches the user must carry a disclaimer.
This is non-negotiable for any legal AI tool.
"""

LEGAL_DISCLAIMER = """
---
**IMPORTANT LEGAL DISCLAIMER**

This analysis is generated by an AI system for **informational and educational purposes only**.
It does **not** constitute legal advice, and should not be relied upon as a substitute for
consultation with a qualified attorney licensed in your jurisdiction.

The AI analysis may contain errors, omissions, or inaccuracies. Laws and regulations vary
by jurisdiction and change over time. **Always consult a licensed attorney** before signing,
modifying, or making decisions based on any legal contract.

*AI Legal Contract Analyzer — Not a law firm. Not your attorney.*
""".strip()

SHORT_DISCLAIMER = (
    "⚠️ AI-generated analysis only. Not legal advice. Consult a qualified attorney before acting."
)


def inject_disclaimer(text: str, short: bool = False) -> str:
    """Append the appropriate disclaimer to any text output."""
    disclaimer = SHORT_DISCLAIMER if short else LEGAL_DISCLAIMER
    return f"{text}\n\n{disclaimer}"


def get_disclaimer(short: bool = False) -> str:
    """Return disclaimer text without modifying input."""
    return SHORT_DISCLAIMER if short else LEGAL_DISCLAIMER
